import { useEffect, useMemo, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Copy, Check, RefreshCw } from 'lucide-react'
import { sileo } from 'sileo'
import Modal from '../Modal'
import { api } from '../../api/client'
import CustomSelect from '../CustomSelect'

function CopyButton({ label, value, disabled = false }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      className="btn-ghost"
      style={{ height: 32, padding: '0 10px' }}
      disabled={disabled}
      onClick={() => {
        navigator.clipboard.writeText(value).then(() => {
          setCopied(true)
          setTimeout(() => setCopied(false), 1600)
        })
      }}
    >
      {copied ? <Check size={12} /> : <Copy size={12} />}
      {copied ? 'Copied' : label}
    </button>
  )
}

function IOSToggle({ checked, disabled, onChange }) {
  return (
    <button
      type="button"
      onClick={() => !disabled && onChange(!checked)}
      aria-pressed={checked}
      style={{
        width: 46,
        height: 26,
        borderRadius: 999,
        border: 'none',
        cursor: disabled ? 'not-allowed' : 'pointer',
        background: checked ? 'var(--accent)' : 'var(--card-3)',
        opacity: disabled ? 0.55 : 1,
        position: 'relative',
        transition: 'background 0.18s ease',
      }}
    >
      <span
        style={{
          position: 'absolute',
          top: 3,
          left: checked ? 23 : 3,
          width: 20,
          height: 20,
          borderRadius: '50%',
          background: checked ? '#0a0a0a' : '#fff',
          transition: 'left 0.18s ease, background 0.18s ease',
          boxShadow: '0 1px 3px rgba(0,0,0,0.35)',
        }}
      />
    </button>
  )
}

export default function SshAccessModal({ instanceName, onClose }) {
  const [loading, setLoading] = useState(false)
  const [toggling, setToggling] = useState(false)
  const [creds, setCreds] = useState(null)
  const [error, setError] = useState('')
  const [selectedHost, setSelectedHost] = useState('')
  const [sshEnabled, setSshEnabled] = useState(false)
  const autoGeneratedRef = useRef(false)

  const instanceQuery = useQuery({
    queryKey: ['instance', instanceName],
    queryFn: () => api.getInstance(instanceName),
    enabled: Boolean(instanceName),
    refetchInterval: 10000,
  })

  const statusQuery = useQuery({
    queryKey: ['ssh-password-status', instanceName],
    queryFn: () => api.getSshPasswordStatus(instanceName, 'ubuntu'),
    enabled: Boolean(instanceName),
  })

  async function generate({ silent = false } = {}) {
    setLoading(true)
    setError('')
    try {
      const result = await api.generateSshPassword(instanceName, {
        username: 'ubuntu',
        password_length: 20,
        enable_password_auth: true,
      })
      setCreds(result)
      setSshEnabled(true)
      if (!silent) sileo.success({ title: `SSH credentials generated for ${instanceName}` })
    } catch (err) {
      setError(err.message || 'Failed to generate SSH credentials')
    } finally {
      setLoading(false)
    }
  }

  async function disablePasswordAccess() {
    setToggling(true)
    setError('')
    try {
      await api.disableSshPassword(instanceName, {
        username: 'ubuntu',
        lock_password: true,
        disable_password_auth: true,
      })
      setSshEnabled(false)
      setCreds(null)
      sileo.success({ title: `SSH password access disabled for ${instanceName}` })
    } catch (err) {
      setError(err.message || 'Failed to disable SSH password access')
      setSshEnabled(true)
    } finally {
      setToggling(false)
    }
  }

  useEffect(() => {
    setCreds(null)
    setSelectedHost('')
    setError('')
    autoGeneratedRef.current = false
  }, [instanceName])

  useEffect(() => {
    const status = statusQuery.data
    if (!status) return
    const enabled = Boolean(status.enabled)
    setSshEnabled(enabled)
    if (enabled && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true
      void generate({ silent: true })
    }
  }, [statusQuery.data])

  const ipOptions = useMemo(() => {
    const fromInstance = Array.isArray(instanceQuery.data?.ipv4) ? instanceQuery.data.ipv4.filter(Boolean) : []
    const merged = [...fromInstance]
    if (creds?.host && !merged.includes(creds.host)) merged.unshift(creds.host)
    return merged.map((ip) => ({ value: ip, label: ip }))
  }, [instanceQuery.data, creds])

  useEffect(() => {
    if (ipOptions.length === 0) return
    setSelectedHost((current) => {
      if (current && ipOptions.some((option) => option.value === current)) return current
      if (creds?.host && ipOptions.some((option) => option.value === creds.host)) return creds.host
      return ipOptions[0].value
    })
  }, [ipOptions, creds])

  const username = creds?.username || statusQuery.data?.username || 'ubuntu'
  const sshCommand = selectedHost ? `ssh ${username}@${selectedHost}` : `ssh ${username}@<instance-ip>`
  const password = creds?.password || ''
  const busy = loading || toggling || statusQuery.isLoading

  async function toggle(nextValue) {
    if (nextValue) {
      setToggling(true)
      try {
        await generate()
      } finally {
        setToggling(false)
      }
      return
    }
    await disablePasswordAccess()
  }

  return (
    <Modal
      title={`SSH Access · ${instanceName}`}
      onClose={onClose}
      size="md"
      footer={(
        <>
          <button className="btn-ghost" onClick={onClose}>Close</button>
          {sshEnabled && (
            <button className="btn-accent" onClick={() => generate()} disabled={busy}>
              <RefreshCw size={13} /> {loading ? 'Generating…' : 'Regenerate'}
            </button>
          )}
        </>
      )}
    >
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
        background: 'var(--card-2)', border: '1px solid var(--border)', borderRadius: 12, padding: '10px 12px',
        marginBottom: 12,
      }}>
        <div>
          <p style={{ margin: 0, fontSize: 12.5, fontWeight: 700, color: 'var(--text-primary)' }}>Password SSH</p>
          <p className="mono" style={{ margin: '4px 0 0', fontSize: 11, color: 'var(--text-secondary)' }}>
            {sshEnabled ? 'Enabled' : 'Disabled'}
          </p>
        </div>
        <IOSToggle checked={sshEnabled} disabled={busy} onChange={toggle} />
      </div>

      {error && (
        <p className="mono" style={{ fontSize: 12, color: 'var(--stopped)', marginTop: 0, marginBottom: 12 }}>
          {error}
        </p>
      )}

      {!sshEnabled ? (
        <p className="mono" style={{ fontSize: 11.5, color: 'var(--text-secondary)', margin: 0 }}>
          Toggle on to enable password SSH and generate a temporary password.
        </p>
      ) : (
        <>
          <div style={{ display: 'grid', gap: 10 }}>
            <div style={{ background: 'var(--card-2)', border: '1px solid var(--border)', borderRadius: 11, padding: '10px 12px' }}>
              <p className="section-label" style={{ marginBottom: 6 }}>Target IP</p>
              {ipOptions.length > 0 ? (
                <CustomSelect
                  value={selectedHost}
                  onChange={setSelectedHost}
                  options={ipOptions}
                  controlHeight={36}
                  style={{ width: '100%' }}
                />
              ) : (
                <p className="mono" style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0 }}>
                  No IP detected yet.
                </p>
              )}
            </div>

            <div style={{ background: 'var(--card-2)', border: '1px solid var(--border)', borderRadius: 11, padding: '10px 12px' }}>
              <p className="section-label" style={{ marginBottom: 6 }}>SSH Command</p>
              <p className="mono" style={{ fontSize: 12, color: 'var(--text-primary)', margin: 0 }}>{sshCommand}</p>
            </div>

            <div style={{ background: 'var(--card-2)', border: '1px solid var(--border)', borderRadius: 11, padding: '10px 12px' }}>
              <p className="section-label" style={{ marginBottom: 6 }}>Password</p>
              <p className="mono" style={{ fontSize: 13, color: 'var(--accent)', margin: 0, wordBreak: 'break-all' }}>
                {password || (loading ? 'Generating…' : '—')}
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: 8, marginTop: 12, flexWrap: 'wrap' }}>
            <CopyButton label="Copy SSH command" value={sshCommand} disabled={!selectedHost} />
            <CopyButton label="Copy password" value={password} disabled={!password} />
            <CopyButton label="Copy both" value={`${sshCommand}\nPassword: ${password}`} disabled={!selectedHost || !password} />
          </div>

          {creds?.note && (
            <p className="mono" style={{ fontSize: 10.5, color: 'var(--text-muted)', marginTop: 10, marginBottom: 0 }}>
              {creds.note}
            </p>
          )}
        </>
      )}
    </Modal>
  )
}
