import { useEffect, useMemo, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Copy, Check, RefreshCw } from 'lucide-react'
import { sileo } from 'sileo'
import Modal from '../Modal'
import Tooltip from '../Tooltip'
import { api } from '../../api/client'
import CustomSelect from '../CustomSelect'
import IOSToggle from '../IOSToggle'

function CopyIconBtn({ value, disabled = false }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      type="button"
      disabled={disabled}
      onClick={() => {
        navigator.clipboard.writeText(value).then(() => {
          setCopied(true)
          setTimeout(() => setCopied(false), 1600)
        })
      }}
      style={{
        background: 'none', border: 'none', padding: 4, cursor: disabled ? 'not-allowed' : 'pointer',
        color: copied ? 'var(--accent)' : 'var(--text-secondary)',
        opacity: disabled ? 0.35 : 1,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        borderRadius: 6, flexShrink: 0,
        transition: 'color 0.13s',
      }}
      onMouseEnter={e => { if (!disabled) e.currentTarget.style.color = 'var(--text-primary)' }}
      onMouseLeave={e => { e.currentTarget.style.color = copied ? 'var(--accent)' : 'var(--text-secondary)' }}
    >
      {copied ? <Check size={13} /> : <Copy size={13} />}
    </button>
  )
}

export default function SshAccessModal({ instanceName, onClose }) {
  const [loading, setLoading]   = useState(false)
  const [toggling, setToggling] = useState(false)
  const [creds, setCreds]       = useState(null)
  const [error, setError]       = useState('')
  const [selectedHost, setSelectedHost] = useState('')
  const [sshEnabled, setSshEnabled]     = useState(false)
  const autoGeneratedRef = useRef(false)

  const instanceQuery = useQuery({
    queryKey: ['instance', instanceName],
    queryFn: () => api.getInstance(instanceName),
    enabled: Boolean(instanceName),
    refetchInterval: 10000,
  })

  const statusQuery = useQuery({
    queryKey: ['ssh-password-status', instanceName],
    queryFn: () => api.getSshPasswordStatus(instanceName, 'ubuntu'),
    enabled: Boolean(instanceName),
  })

  async function generate({ silent = false } = {}) {
    setLoading(true)
    setError('')
    try {
      const result = await api.generateSshPassword(instanceName, {
        username: 'ubuntu',
        password_length: 20,
        enable_password_auth: true,
      })
      setCreds(result)
      setSshEnabled(true)
      if (!silent) sileo.success({ title: `SSH credentials generated for ${instanceName}` })
    } catch (err) {
      setError(err.message || 'Failed to generate SSH credentials')
    } finally {
      setLoading(false)
    }
  }

  async function disablePasswordAccess() {
    setToggling(true)
    setError('')
    try {
      await api.disableSshPassword(instanceName, {
        username: 'ubuntu',
        lock_password: true,
        disable_password_auth: true,
      })
      setSshEnabled(false)
      setCreds(null)
      sileo.success({ title: `SSH password access disabled for ${instanceName}` })
    } catch (err) {
      setError(err.message || 'Failed to disable SSH password access')
      setSshEnabled(true)
    } finally {
      setToggling(false)
    }
  }

  useEffect(() => {
    setCreds(null)
    setSelectedHost('')
    setError('')
    autoGeneratedRef.current = false
  }, [instanceName])

  useEffect(() => {
    const status = statusQuery.data
    if (!status) return
    const enabled = Boolean(status.enabled)
    setSshEnabled(enabled)
    if (enabled && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true
      void generate({ silent: true })
    }
  }, [statusQuery.data])

  const ipOptions = useMemo(() => {
    const fromInstance = Array.isArray(instanceQuery.data?.ipv4) ? instanceQuery.data.ipv4.filter(Boolean) : []
    const merged = [...fromInstance]
    if (creds?.host && !merged.includes(creds.host)) merged.unshift(creds.host)
    return merged.map((ip) => ({ value: ip, label: ip }))
  }, [instanceQuery.data, creds])

  useEffect(() => {
    if (ipOptions.length === 0) return
    setSelectedHost((current) => {
      if (current && ipOptions.some((o) => o.value === current)) return current
      if (creds?.host && ipOptions.some((o) => o.value === creds.host)) return creds.host
      return ipOptions[0].value
    })
  }, [ipOptions, creds])

  const username   = creds?.username || statusQuery.data?.username || 'ubuntu'
  const sshCommand = selectedHost ? `ssh ${username}@${selectedHost}` : `ssh ${username}@<instance-ip>`
  const password   = creds?.password || ''
  const busy       = loading || toggling || statusQuery.isLoading

  async function toggle(nextValue) {
    if (nextValue) {
      setToggling(true)
      try { await generate() } finally { setToggling(false) }
      return
    }
    await disablePasswordAccess()
  }

  return (
    <Modal title={`SSH Access · ${instanceName}`} onClose={onClose} size="md">
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
        paddingBottom: 10, marginBottom: 12, borderBottom: '1px solid var(--border)',
      }}>
        <div>
          <p style={{ margin: 0, fontSize: 12.5, fontWeight: 700, color: 'var(--text-primary)' }}>Password SSH</p>
        </div>
        <IOSToggle checked={sshEnabled} disabled={busy} onChange={toggle} />
      </div>

      {error && (
        <p className="mono" style={{ fontSize: 12, color: 'var(--stopped)', marginTop: 0, marginBottom: 12 }}>
          {error}
        </p>
      )}

      {!sshEnabled ? (
        <p className="mono" style={{ fontSize: 11.5, color: 'var(--text-secondary)', margin: 0 }}>
          Toggle on to enable password SSH and generate a temporary password.
        </p>
      ) : (
        <div style={{ display: 'grid', gap: 10 }}>
          <div style={{ padding: '2px 0 10px' }}>
            <p className="section-label" style={{ marginBottom: 6 }}>Target IP</p>
            {ipOptions.length > 0 ? (
              <CustomSelect value={selectedHost} onChange={setSelectedHost} options={ipOptions} controlHeight={36} style={{ width: '100%' }} />
            ) : (
              <p className="mono" style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0 }}>No IP detected yet.</p>
            )}
          </div>

          <div style={{ padding: '10px 0', borderTop: '1px solid var(--border)' }}>
            <p className="section-label" style={{ marginBottom: 6 }}>SSH Command</p>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <p className="mono" style={{ fontSize: 12, color: 'var(--text-primary)', margin: 0, flex: 1, wordBreak: 'break-all' }}>{sshCommand}</p>
              <Tooltip label="Copy command">
                <CopyIconBtn value={sshCommand} disabled={!selectedHost} />
              </Tooltip>
            </div>
          </div>

          <div style={{ padding: '10px 0', borderTop: '1px solid var(--border)' }}>
            <p className="section-label" style={{ marginBottom: 6 }}>Password</p>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <p className="mono" style={{ fontSize: 13, color: 'var(--accent)', margin: 0, flex: 1, wordBreak: 'break-all' }}>
                {password || (loading ? 'Generating…' : '—')}
              </p>
              <Tooltip label="Regenerate">
                <button
                  type="button"
                  disabled={busy}
                  onClick={() => generate()}
                  style={{
                    background: 'none', border: 'none', padding: 4, cursor: busy ? 'not-allowed' : 'pointer',
                    color: 'var(--text-secondary)', opacity: busy ? 0.35 : 1,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    borderRadius: 6, flexShrink: 0, transition: 'color 0.13s',
                  }}
                  onMouseEnter={e => { if (!busy) e.currentTarget.style.color = 'var(--text-primary)' }}
                  onMouseLeave={e => { e.currentTarget.style.color = 'var(--text-secondary)' }}
                >
                  <RefreshCw size={13} style={loading ? { animation: 'spin 0.7s linear infinite' } : {}} />
                </button>
              </Tooltip>
              <Tooltip label="Copy password">
                <CopyIconBtn value={password} disabled={!password} />
              </Tooltip>
            </div>
          </div>

          {creds?.note && (
            <p className="mono" style={{ fontSize: 10.5, color: 'var(--text-muted)', margin: 0 }}>
              {creds.note}
            </p>
          )}
        </div>
      )}
    </Modal>
  )
}
